# Auto update from Guizhan Build is enabled by default.
# Auto update or not.
auto-update: true
# Build station to use.
build-station: "Guizhan" # Expected "Guizhan" / "Blob"

# Do not change this value unless you know what you are doing.
config-version: C_20250301_1

max-content-per-page: 5

# Do not change this value unless you know what you are doing.
debug: false

database:
  type: sqlite # Expected sqlite / mysql

  # Note: This feature has not been fully tested!!! Use it at your own risk.
  mysql:
    host: 127.0.0.1
    port: 3306
    database: ""
    user: ""
    password: ""
    useSSL: false
    timezone: Shanghai
    maxConnection: 10
  # Note: This feature has been fully tested.
  sqlite:
    maxConnection: 3
